#!/bin/bash
##------------------------##
##--Find Network Gataway--##
##------------------------##
##make lock file
rm /tmp/lock 2>/dev/null ; touch /tmp/lock
## make loading
loading(){
    while [ -f "/tmp/lock" ] ; do
    echo -ne "\r| Loading |"
	sleep 0.05
	echo -en "\r/ Loading /"
	sleep 0.05
	echo -en "\r- Loading -"
	sleep 0.05
	echo -en "\r\\ Loading \\"
	sleep 0.5
	done
}
loading &
getaway=`ip addr | grep inet | grep -v inet6 | grep -v 127.0 | awk {'print $2'} | awk {'print $1'} | sed 's/[/].*$//g' |  grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}'`
getaway="$getaway".0-255
##------------------------##
##-----Check Clients------##
##------------------------##
nmap -sP $getaway | grep report | sed 's/Nmap scan report for //g' > /tmp/wifi-killer-output ; rm /tmp/lock
echo -e "\rThe Resualt Is :"
cat /tmp/wifi-killer-output
##Coded By Https://github.com/pouya-abbasian
