#!/bin/bash
##------------------------##
##--Find Network Gataway--##
##------------------------##
getaway=`ip addr | grep inet | grep -v inet6 | grep -v 127.0 | awk {'print $2'} | awk {'print $1'} | sed 's/[/].*$//g' |  grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}'`
getaway="$getaway".0-255
##------------------------##
##-----Check Clients------##
##------------------------##
nmap -sP $getaway | grep report | sed 's/Nmap scan report for //g'
##Coded By Https://github.com/pouya-abbasian
